packages:
  - .
  - template
catalogs:
  build:
    unbuild: ^3.6.1
    vitepress: ^1.6.4
  cli:
    bumpp: ^10.3.1
    pncat: ^0.7.4
    taze: ^19.8.1
  lint:
    '@antfu/eslint-config': ^6.1.0
    eslint: ^9.38.0
    lint-staged: ^16.2.6
    prettier: ^3.6.2
    simple-git-hooks: ^2.13.1
  markdown:
    turndown: ^7.2.2
  node:
    '@clack/prompts': ^0.11.0
    ansis: ^4.2.0
    cac: ^6.7.14
    execa: ^9.6.0
    fs-extra: ^11.3.2
    pathe: ^2.0.3
    rimraf: ^6.0.1
    tinyglobby: ^0.2.15
    unconfig: ^7.3.3
  script:
    tsx: ^4.20.6
  test:
    vitest: ^4.0.4
  tsc:
    typescript: ^5.9.3
  types:
    '@types/fs-extra': ^11.0.4
    '@types/node': ^24.9.2
    '@types/turndown': ^5.0.6
  utils:
    cheerio: ^1.1.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
