packages:
  - .
  - template
catalogs:
  build:
    unbuild: ^3.6.0
    vitepress: ^1.6.3
  cli:
    bumpp: ^10.2.2
    czg: ^1.12.0
    pncat: ^0.4.0
    taze: ^19.1.0
  dev:
    '@octohash/tsconfig': ^0.1.0
    typescript: ^5.9.2
  lint:
    '@antfu/eslint-config': ^5.0.0
    eslint: ^9.32.0
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.1
  markdown:
    turndown: ^7.2.0
  node:
    '@clack/prompts': ^0.11.0
    ansis: ^4.1.0
    cac: ^6.7.14
    execa: ^9.6.0
    fs-extra: ^11.3.0
    pathe: ^2.0.3
    rimraf: ^6.0.1
    tinyglobby: ^0.2.14
    unconfig: ^7.3.2
  script:
    tsx: ^4.20.3
  test:
    vitest: ^3.2.4
  types:
    '@types/fs-extra': ^11.0.4
    '@types/node': ^24.1.0
    '@types/turndown': ^5.0.5
  utils:
    cheerio: ^1.1.2
